spring:
  profiles:
    include:
      - db
      - doc
      - json
      - vault
      - aws
    groups:
      - prod
      - dev
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
server:
  origin: http://teemohouse.techteemo.store:8080

---
spring:
  config:
    activate:
      on-profile: prod
server:
  origin: https://teemoshopping.techteemo.store
